version: '3.9'

services:
  batch-localstack:
    image: localstack/localstack:latest
    container_name: sqs-test-localstack
    ports:
      - '4566:4566'
      - '4576:4576'
    environment:
      - SERVICES=sqs
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test