services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
