services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=off
      -c log_min_duration_statement=0
      -c log_connections=on
      -c log_disconnections=on
      -c client_min_messages=log

  # api:
  #   build: .
  #   container_name: go-api-server
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
  #     - postgres
  #   environment:
  #     - REDIS_ADDR=redis:6379
