// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/input.proto

package input

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InputService_SendKey_FullMethodName = "/input.InputService/SendKey"
)

// InputServiceClient is the client API for InputService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InputServiceClient interface {
	SendKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KeyResponse, error)
}

type inputServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInputServiceClient(cc grpc.ClientConnInterface) InputServiceClient {
	return &inputServiceClient{cc}
}

func (c *inputServiceClient) SendKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, InputService_SendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputServiceServer is the server API for InputService service.
// All implementations must embed UnimplementedInputServiceServer
// for forward compatibility.
type InputServiceServer interface {
	SendKey(context.Context, *KeyRequest) (*KeyResponse, error)
	mustEmbedUnimplementedInputServiceServer()
}

// UnimplementedInputServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInputServiceServer struct{}

func (UnimplementedInputServiceServer) SendKey(context.Context, *KeyRequest) (*KeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendKey not implemented")
}
func (UnimplementedInputServiceServer) mustEmbedUnimplementedInputServiceServer() {}
func (UnimplementedInputServiceServer) testEmbeddedByValue()                      {}

// UnsafeInputServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InputServiceServer will
// result in compilation errors.
type UnsafeInputServiceServer interface {
	mustEmbedUnimplementedInputServiceServer()
}

func RegisterInputServiceServer(s grpc.ServiceRegistrar, srv InputServiceServer) {
	// If the following call pancis, it indicates UnimplementedInputServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InputService_ServiceDesc, srv)
}

func _InputService_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputServiceServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputService_SendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputServiceServer).SendKey(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InputService_ServiceDesc is the grpc.ServiceDesc for InputService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InputService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "input.InputService",
	HandlerType: (*InputServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendKey",
			Handler:    _InputService_SendKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/input.proto",
}
